### ISSUE TITLE
Probably unnecessary using statement.

### ISSUE THREAD

**Issue by edharfmann** [wleev/Catnap.Server#2]
In HttpServer.cs, WriteResponse, line 89.  I understand that stream needs a using statement, but I THINK the using statement for the output variable is wrong as it is accessing the OutputStream, not creating a new instance that needs to be disposed.  (My implementation had some 'strangeness' that cleared up after I removed that using.)

Please review and if you concur, please update.

Thank you VERY MUCH for a great implementation.

Ed

**Comment by wleev** [comment]
You are absolutely right. I'll push the update as soon as I am able.
